# Base configs
#baseurl: "https://joebrew.net"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography | Joe Brew"
subtitle: "family, health, development, travel"
author: "Joe Brew"
header:
 title: "Photography"
 subtitle: "by Joe Brew"
footer:
 name: "Joe Brew"
 bio: "I am a guy who does things and sometimes takes a camera along."
 github: "Want to know more about me? Click <a href=\"https://joebrew.net\">here</a>."
social_urls:
  facebook: "https://www.facebook.com/josephbrew"
  twitter: "https://www.twitter.com/joethebrew"
  instagram: "https://www.instagram.com/brew.joe"
  linkedin: "https://linkedin.com/in/joe-brew-1061a33a/"
  github: "https://www.github.com/joebrew"
